name: Jasper-Osborne Escapades
favicon: null
layout_spectrum: 1
typography_spectrum: 0.26382
title: Jasper-Osborne Escapades
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dae9e6'
    - '#768b9e'
    - '#10110c'
    - '#6b7731'
    - '#aab9bc'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
