name: Jasper-Osborne Escapades
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2622366186697036
title: Jasper-Osborne Escapades
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#975e27'
    - '#5c2009'
    - '#ffa183'
    - '#c68c5d'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
