name: Jasper-Osborne Escapades
favicon: null
layout_spectrum: 0.23070660140365362
typography_spectrum: 0.2622366186697036
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5658110566437244
  lightness: 0.525136376498267
  saturation: 0.33507616771385074
  rhythmicContrast: 0.9620725680142641
purpose: []
